name: PR Checks for Dev Environment

on:
  pull_request:
    branches:
      - dev

jobs:
  pr-checks:
    runs-on: self-hosted
    strategy:
      matrix:
        label: [dev]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build the project
        run: npm run build
